### ISSUE TITLE
Parameters tuning of verkko pipeline for plant assemblies

### ISSUE THREAD

**Issue by baozg** [marbl/verkko#102]
Hi, 

I have run the whole verkko pipeline for some inbreeding plant with HiFi and UL reads. I have found the verkko graph look is very promsing (number of large contigs is close to the total chromosomes). But the final contigs have been broken into different piece (3x of total chromosomes). I am wondering if there any step can tune the parameters?  Do you have any suggesstions like Canu documents ?

- MBG
- GraphAligner

Thanks in advance.

**Comment by maickrau** [comment]
Hi, it's a bit difficult to say without looking at the assembly. If you're willing to share the intermediate files then we might see what's going on. Here's instructions how to share data: https://canu.readthedocs.io/en/latest/faq.html#how-can-i-send-data-to-you

**Comment by baozg** [comment]
Hi, Mikko

What intermediate files do you need?
- Final assembly and graph
- MBG graph
- ONT align gaf

Anything else?

**Comment by maickrau** [comment]
The key files are:
- `1-buildGraph/hifi-resolved.gfa`
- `1-buildGraph/paths.gaf`
- `2-processGraph/unitig-unrolled-hifi-resolved.gfa`
- `2-processGraph/unitig-unrolled-hifi-resolved.*coverage.csv`
- `4-processONT/alns-ont-mapqfilter.gaf`
- `4-processONT/gapped-unitig-unrolled-hifi-resolved.gfa`
- `4-processONT/connected.gfa`
- `4-processONT/ont-resolved-graph.gfa`
- `5-untip/unitig-unrolled-ont-resolved.*coverage.csv`
- `6-layoutContigs/combined-nodemap.txt`
- `assembly.*`

**Comment by baozg** [comment]
But the `5-untip` didn't have any `unitig-unrolled-ont-resolved.*coverage.csv`. All I have just the following staff

<img width="852" alt="image" src="https://user-images.githubusercontent.com/20680150/190189779-299a6bdd-b6fd-48f2-924b-437a0d3fb775.png">

**Comment by maickrau** [comment]
I misremembered the name. That one should be `5-untip/unitig-popped-unitig-normal-connected-tip.*coverage.csv`

**Comment by baozg** [comment]
Hi, @maickrau 

Could the data be accessible for you? I recently update two accession result with one more cell, should I update these?

**Comment by skoren** [comment]
Switching from #111 to here.

First, if you want to re-run with v1.2 you can start from corrected hifi reads, there's no changes in correction. You can also try the latest MBG which isn't in v1.2 but has some new features to simplify the hifi graph more.

I took a look at a couple of the graphs. The tangles that aren't resolved look reasonable, I think they are not being resolved because they are too long for the ONT reads (at least 90-100kb in compressed space which is 150kb in uncompressed space and some longer). The coverage in some tangles is also quite low. We've seen a few regions where the HiFi data can't sequence through gaps leading to no or very depressed coverage. ONT also has some trouble sequencing through these regions so that may explain why they are not being resolved. For example here's what's like a 2-copy repeat that's over 200kb long:
<img width="753" alt="Screen Shot 2022-11-18 at 11 14 00 AM" src="https://user-images.githubusercontent.com/923478/202751163-ce47815a-3a23-4a8e-baa5-51824a04b567.png">

There's also still some heterozygosity despite it being inbreeding lines, here's an example of that:
<img width="723" alt="Screen Shot 2022-11-18 at 11 08 58 AM" src="https://user-images.githubusercontent.com/923478/202751353-713d6582-b0e2-4029-b910-b018cd742d9a.png">

So I don't think there's anything to adjust in terms of parameters, verkko is being intentionally conservative here. There are some thresholds for accepting a resolution you could modify to make the resolution not at least twice as well supported as the rest (in src/scripts/pick_majority_bridge.py) but that can introduce errors. It would be helpful if you have ONT alignments of reads around some of these gaps that span them (you can align to the final assembly) but still see them as unresolved, we can take a look at why that is the case.

**Comment by baozg** [comment]
Thank you so much for the detailed explanation. I already run verkko 1.2 with more sequencing data (twice > 100kb UL reads as before), let's see if verkko can resolve more tangles. It makes sense that 100kb UL reads cannot span some repeats, my species have uncanonical centromere (~3kb monomer unit vs human 178bp). So even though we have 60x > 100kb reads, some repeats cannot be resolved, right?

After this run, I will map all ONT reads to the final assembly to see what happens in the gap region.

**Comment by skoren** [comment]
Yes, there are usually a few regions that aren't resolved but hopefully the extra data and v1.2 will help. Let us know if you find spanning reads for a gap that isn't resolved and we can check why (not sufficiently better than others for example) as it might help identify cases where we can improve Verkko's resolution.

**Comment by skoren** [comment]
FYI, we found an issue in some plants where very large GA-rich sequence are not properly mapped by graphaligner and are missing in the HiFi data. The 1.2 release page has the info, you can adjust the ```--seed-max-length 100000``` which will be slower but should address the missing mappings. This has improved the plant assemblies we've tried it on so I suggest trying it on yours as well.

**Comment by baozg** [comment]
Thanks for the information, I will try to adjust the `--seed-max-length`

**Comment by skoren** [comment]
The fix for this is incorporated in the latest GraphAligner available on conda and verkko tip code. Both will be part of the next verkko release.
