### ISSUE TITLE
--paths doesn't find ONT reads unless --nano is supplied.

### ISSUE THREAD

**Issue by brianwalenz** [marbl/verkko#121]
```
verkko \
  --paths some.gaf \
  --assembly some-assembly \
  -d some-output \
  --hifi hifi/*fastq.gz
```
will fail to include ONT reads even if they exist in `some-assembly` because 7-buildPackages.sm sets the ont subset file to `emptyfile` if there are not ONT reads supplied to verkko:
```
checkpoint buildPackages:
    input:
        hifi       = HIFI_READS,
        layout     = {rules.layoutContigs.output.layout},
        ont_subset = {rules.extractONT.output.ont_subset} if config['withONT'] == "True" else {rules.emptyfile.output}
```

**Comment by skoren** [comment]
I think we should just parse the snakemake parameters for the provided assembly folder and add all its hifi and ONT data automatically to the parameters w/o the user doing anything. Since we have a list of what reads went into the original asm, it should be natural to include them all. Any files the user provides can be used as additional reads if needed.

**Comment by skoren** [comment]
Fixed, --paths will now inherit the ONT and HiFI data from the previous asm.
