### ISSUE TITLE
Assemby Arabidopsis results are greater than real

### ISSUE THREAD

**Issue by zwycookies** [marbl/verkko#137]
Dear developer,
     I first try to test verkko for Arabidopsis data which is mentioned in your paper (data from the paper 'High-quality Arabidopsis thaliana Genome Assembly with Nanopore and HiFi Long Reads'). I used Pacbio hifi and ont data download from big database and using the default parameters follow your github (verkko -d asm_res/ --hifi hifi/CRR302668.fastq.gz --nano ont/CRR302667.fastq.gz --local-cpus 30 --local-memory 128). However, I got a final assembly genome of 182 Mb with 2255 contigs which is much bigger than the real Arabidopsis genome (~130 Mb). Am I miss some important steps during verkko analysis ?

    Thanks,
    Weiyi.

**Comment by skoren** [comment]
In short, the extra sequence is likely redundant with other sequences (haplotype differences, rDNA, and plastid genomes usually count for most of this). The full dataset is also extremely deep as well, for the paper we used a subset of about 100x HiFi and 200x ONT which likely reduced some of the redundancy (see my comments regarding N50 in #37). That said, the final assembly in the paper was about 160 Mbp and I'm not sure 130 Mbp is the full genome or if some repetitive regions are excluded in that total.

Since issue #37 we've added a filtering option to verkko to remove mito/rDNA and similar. You can pass the option `--screen mito <path to mito sequence>.fasta`. An arbitrary number of things to screen for are allowed. I would suggest adding a screen for mito and rDNA and chloroplast and see what the updated assembly size is then.

**Comment by skoren** [comment]
Idle
