### ISSUE TITLE
v1.4: assertionerror in ont resolve graph

### ISSUE THREAD

**Issue by ptrebert** [marbl/verkko#164]
Hi,

I have two v1.4 runs with the following assertion failing:

```
>>> file: ont_resolved_graph.gfa.err
>>> ont resolve error
resolve k=8423, extended 1 nodes into 2 nodes
resolve hairpin >utig1-11098
Traceback (most recent call last):
File "[...]/lib/verkko/scripts/resolve_triplets_kmerify.py", line 1031, in <module>
resolve(node_lens, edge_overlaps, node_seqs, edges, paths_crossing, coverage, min_allowed_coverage, removable_nodes)
File "[...]/lib/verkko/scripts/resolve_triplets_kmerify.py", line 744, in resolve
assert len(resolved) == 0
AssertionError
```

I can share the Verkko run directory for debugging purposes, but only via Globus (push or pull).

Best,
Peter

**Comment by ptrebert** [comment]
actually, 3 failed runs here; I am transferring subfolders 2- and 4- to the T2T share

**Comment by maickrau** [comment]
This should be fixed in [4f6a54e](https://github.com/marbl/verkko/commit/4f6a54e37a65dde7858f4f8111b54fea42b74c76), the ont multiplex resolution didn't properly handle the case where the node is a hairpin disconnected from everything. Now it leaves them unresolved because they're probably spurious nodes, at least in the first case it was.

**Comment by ptrebert** [comment]
Surprisingly, ignoring the problem has fixed it ;-)
I copied the changed script into my Verkko installation as before, and the three runs now completed successfully. Thanks.

**Comment by ptrebert** [comment]
... would be nice to see a Verkko bugfix release nevertheless, of course
