### ISSUE TITLE
Run with ONT only

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [marbl/verkko#169]
Is it possible to add an option to run with ONT only?

Thanks.

**Comment by skoren** [comment]
If you mean duplex, you can just pass them using the --hifi option. Standard simplex reads aren't compatible with verkko as they don't have large enough k-mers to build the initial graph so we aren't planning to add support for that.

**Comment by OZTaekOppa** [comment]
Hi @theo-allnutt-bioinformatics and @skoren,

Hope this email finds you well.

I am really interested in your duplex approach for humans, plants and animals. Is there any progress?
Adding to this, is there any chance to use the Pore-C approach over Hi-C reads?

FYI,
https://github.com/epi2me-labs/pore-c-py
https://github.com/nanoporetech/Pore-C-Snakemake

At this moment, I do not have any trio dataset so, I am trying to stick with Hi-C mode to produce a phased T2T assembly.
Is this the proper pipeline for my scenario? 

Based on the manual, it says as below:
# To run in Hi-C mode, reads should be provided using the --hic1 and --hic2 options. For example:

verkko -d asm \
  --hifi hifi/*.fastq.gz \
  --nano ont/*.fastq.gz \
  --hic1 hic/*R1*fastq.gz  \
  --hic2 hic/*R2*fastq.gz

--hifi: Can be replaced with ONT duplex reads
--nano: Will be ONT Ultra-Long reads
--hc1 and --hic2: Is it possible to use Pore-C data instead of Hi-C reads?

If not able to integrate with the current pipeline (replacing Hi-C data with Pore-C), what would be the best way to produce phased T2T assembly using PBHiFi (can be replaced with ONT duplex), ONT Ultra-Long and Pore-C data?

Looking forward to your reply!

**Comment by skoren** [comment]
We plan to add Pore-C support in the near future, it should be straightforward, just switching out the mapper. In the meantime, you can use the GFAse phasing pipeline after verkko to use Pore-C data. See https://github.com/rlorigro/GFAse and https://github.com/Dmitry-Antipov/verkkohic/blob/master/gfase_wrapper.sh

**Comment by KANGYUlab** [comment]
> We plan to add Pore-C support in the near future, it should be straightforward, just switching out the mapper. In the meantime, you can use the GFAse phasing pipeline after verkko to use Pore-C data. See https://github.com/rlorigro/GFAse and https://github.com/Dmitry-Antipov/verkkohic/blob/master/gfase_wrapper.sh

Does the current Verkko v2.1 add GFAse? 
Thanks.

**Comment by skoren** [comment]
We have a native version of HiC/PoreC support which is available in v2.1. See the README for details on how to use it.
