### ISSUE TITLE
v1.4: subsequent phasing - empty haplotype files

### ISSUE THREAD

**Issue by ptrebert** [marbl/verkko#170]
Hi,
I have seen #78 , so I am not sure if that is "by design" or a minor bug. I restarted Verkko with the options `--paths` and `--assembly` to get to a phased assembly using Strand-seq data. After the successful run, the `assembly.fasta` contains contig names indicating the haplotype, but the respective other FASTA files (hap1/2 and unassigned) are empty. Is there a way to get Verkko to split the main FASTA immediately, or do I have to do this manually afterwards?
Thanks.
Best,
Peter

**Comment by skoren** [comment]
Yeah, the paths option doesn't split the reads because it doesn't know anything about the haplotype information to split on. You can use the fasta_extract.py script in verkko along with a list of contigs to extract relevant sequences. However, you can leave this open for us to think about how to supply the relevant info on labels to do that automatically.

**Comment by ptrebert** [comment]
ok, so this is a request for a minor enhancement then :+1:

**Comment by skoren** [comment]
We should enable automatic partitioning of haplotypes based on user-supplied labels when running with the paths option

**Comment by skoren** [comment]
Tracking this in #241
