### ISSUE TITLE
hic-phasing key error

### ISSUE THREAD

**Issue by jlipovac** [marbl/verkko#173]
Hi,

I was running verkko with hifi + UL + OmniC and it finished. After that I tried to run duplex + UL + OmniC using the same UL and OmniC reads as in the previous run. In hic_phasing I got a key error.
I'm attaching hic_phasing.err. [hic_phasing.err.txt](https://github.com/marbl/verkko/files/12049438/hic_phasing.err.txt)

Any idea what could be a problem?

**Comment by Dmitry-Antipov** [comment]
This is definitely a bug, exploring..
May I ask you to attach hicverkko.log (same folder as hic_phasing.err.txt)?

**Comment by jlipovac** [comment]
That file is empty

**Comment by Dmitry-Antipov** [comment]
Likely I've found this bug. May I ask you to replace <VERKKO_DIR>/lib/verkko/scripts/cluster.py  with current https://github.com/marbl/verkko/blob/master/src/scripts/cluster.py and rerun with the same parameters amd output dir ?

**Comment by jlipovac** [comment]
Now it works :) Thanks

**Comment by Dmitry-Antipov** [comment]
This issue was likely connected to the weird case when alignment length reported by mashmap is significantly larger that the length of one of the sequences. Although it is really weird, we've already seen that for mashmap2 for highly repetitive sequences. Now added additional checks, so it will not cause the crash.
