### ISSUE TITLE
Error in rule processGraph

### ISSUE THREAD

**Issue by Ne0tea** [marbl/verkko#177]
Hi!
I'm running latest verkko v1.4.0 with commands as 
`
verkko -d ./ --threads $threads --hifi $fq_dir/HLW_hifi.fastq.gz $fq_dir/HLW_hifi_2.fastq.gz --hic1 $fq_dir/HLW_hic_merged_1.fastq.gz --hic2 $fq_dir/HLW_hic_merged_2.fastq.gz --no-nano --no-correction --local-memory 200 --local-cpus $threads
`
And it reported an error as 
`Error in rule processGraph:
    jobid: 4
    input: 1-buildGraph/hifi-resolved.gfa, 1-buildGraph/paths.gaf
    output: 2-processGraph/unitig-unrolled-hifi-resolved.gfa, 2-processGraph/unitig-mapping-1.txt
    log: 2-processGraph/process.err (check log file(s) for error details)
    shell:`
I can't find anything wrong with it. So, do you have any suggestion to avoid this issue? 
The log record was attached.
[process.err.log](https://github.com/marbl/verkko/files/12161487/process.err.log)

**Comment by Ne0tea** [comment]
Thanks for your reply！
I will try to share the folders and rerun the command without `--no-correction`

**Comment by Ne0tea** [comment]
I have uploaded the 1-* and 2-* folders. Is there any advice with the data?

**Comment by skoren** [comment]
I see files uploaded from those folders on Jul 26. However, when I run them locally I don't get an error. I also saw that the files unitig-unrolled-hifi-resolved.gfa exists and looks OK. I'm not sure hwy snakemake returned an error. What happens if you run verkko with the `--snakeopts --touch` and `--snakeopts --dry-run` and see if it considers the job complete.

**Comment by skoren** [comment]
Idle, unable to reproduce locally.
