### ISSUE TITLE
Not running final consensus since no rukki paths provided!

### ISSUE THREAD

**Issue by xfcypeng** [marbl/verkko#185]
bases=\`expr 3000000000 / 2 \`
 /home/ps/anaconda3/envs/verkko/lib/verkko/scripts/fasta_partition.py \\
  partition split/ont \$bases 150000 0 \\
  tip_reads_compressed.fasta \\
&& \\
touch ../3-alignTips/splitONT.finished
EOF

chmod +x ./splitONT.sh

./splitONT.sh > ../3-alignTips/splitONT.err 2>&1
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-08-19T222948.984736.snakemake.log
ERROR!
Not running final consensus since no rukki paths provided!

**Comment by brianwalenz** [comment]
What's in `3-alignTips/splitONT.err` and what files are present in that directory (`ls -l 3-alignTips/`)?

**Comment by xfcypeng** [comment]
./splitONT.sh; 2: set; Illegal option -o pipefail

**Comment by skoren** [comment]
I think this is because some systems (like Ubuntu) link sh to dash which doesn't support the bash set options. Could you try changing the splitONT.sh file to be:
```
#!/bin/bash
```
instead of
```
#!/bin/sh
```
and run it manually to see if it completes?

**Comment by scorreard** [comment]
Hi team! Thanks for the great tool
I just had the same issue, and editing the file to include '#!/bin/bash' worked.

I saw that this update is already in your GitHub code, but not included in the latest release. Do you know when you will do another release?

Thanks!

**Comment by dazhuang420** [comment]
hi, 
I met the same problem.Not running final consensus since no rukki paths provided!

Then I went to check my intermediate files and found that in the. /4-processONT step, many intermediate files were 0. At the end of the processONT.err file is
Step 15b

Step 16。
By looking at processONT.sh, I found that the program didn't run successfully, and then I tried to run it again, and found that after echo 3b, echo ""
Error will be reported before echo solid ont coverage $ ont _ solid _ cov and hifi $ hifi _ solid _ cov: inserted 3175 gaps.
inserted 7 gaps
inserted 11 gaps
/opt/gridview//pbs/dispatcher/mom_priv/jobs/8924747.admin1.SC: line 117: unexpected EOF while looking for matching ``'。
Do you know the reason?
by the way ,i tried to change  the processONT.sh file to be: #!/bin/bash
Thanks!

**Comment by skoren** [comment]
This is unlikely to be the same problem as it's in a different step, I'm going to open a new issue.

**Comment by dazhuang420** [comment]
Thank you very much. I look forward to your reply. I am now completing processONT.sh step by step, and now I have succeeded in Step 4b. Strangely, if I run processONT.sh directly, I will get an error:
Traceback (most recent call last):
File "/public/home/caijing_lab/zhaodazhuang/anaconda3/lib/verkko/scripts/add_hairpin_uniques.py", line 70, in <module>
assert node in nodelens
^^^^^^^^^^^^^^^^
AssertionError
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
FileNotFoundError: [Errno 2] No such file or directory
/opt/gridview//pbs/dispatcher/mom_priv/jobs/8924815.admin1.SC: line 67: bridges.txt: No such file or directory
Traceback (most recent call last):
File "/public/home/caijing_lab/zhaodazhuang/anaconda3/lib/verkko/scripts/fix_diploid_paths.py", line 85, in <module>
with open(counted_paths_file) as f:
^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'bridges.txt'
Traceback (most recent call last):
File "/public/home/caijing_lab/zhaodazhuang/anaconda3/lib/verkko/scripts/forbid_unbridged_tangles.py", line 8, in <module>
picked_connections_file = sys.argv[4]
~~~~~~~~^^^
IndexError: list index out of range
So now I can only run the program step by step. The problem found should be between 4b and step 5:/public/home/caijing _ lab/zhaodazhuang/anaconda3/lib/verkko/scripts/ add_hairpin_uniques.py unique_nodes_diploidfix.txt hifi-nodecov-gapped-unitig-unrolled-hifi-resolved.csv < gapped-unitig-unrolled-hifi-resolved.gfa \
> unique_nodes_hairpinfix.txt will run with an error message:
Traceback (most recent call last):
File "/public/home/caijing_lab/zhaodazhuang/anaconda3/lib/verkko/scripts/add_hairpin_uniques.py", line 70, in <module>
assert node in nodelens
^^^^^^^^^^^^^^^^
AssertionError
I hope you can help me solve it, thank you very much ~

**Comment by skoren** [comment]
It doesn't make sense why running it in the script would be any different than running it step by step, especially since it seems to be missing many intermediate files along the way. What are the versions of verkko you're running and what are you input data types and coverages?

**Comment by dazhuang420** [comment]
Hello, I ran step by step just to see which step went wrong. As you said, many intermediate files were empty, so although it was also output to 16, the problem was between 4b and step 5. My assembly command is: verkko-d a assemble-hifiall _ hifi.fq.gz-nanoul _ corrected.fa.gz-hic1ic/* R1 *. gz-hic2hic/* R2 *. gz-no-correction. The hifi and ont data here are basically 30X coverage.

**Comment by skoren** [comment]
Your commands/logs are coming through very garbled, like the above Verkko command is missing spaces and the options don't match what verkko uses so is impossible to interpret. The same was true for the initial command logs. 

You also haven't let us know what the input coverages are as I asked above? The node in nodelens error is unlikely to be the original error and I don't want to chase issues created by incomplete re-runs. I'd suggest completely removing the 4-processONT folder and re-running the same verkko command to let it run this step from scratch. Then upload the full log of the run here so we can see what the original error is.
