### ISSUE TITLE
processGraph "assert edge[0] not in node_cuts"

### ISSUE THREAD

**Issue by grinning-bat** [marbl/verkko#230]
Hi! I've probably met #147 again.

**processGraph** failed several times (first it was not activating envo, so unrelated). Being rerun manually gives some lines of:
`can't fix >62706 >62705 due to overlap (wanted 112, overlap 1686)`
interspersed among 
`mend <37326 <45168`

then:
<pre>Traceback (most recent call last):
  File "[redacted]/verkko/env/lib/verkko/scripts/fix_haplogaps.py", line 231, in <module>
    assert edge[0] not in node_cuts</pre>

We are trying to assemble repeat-rich genome of unknown size.
Judging from ONT-only assembly size PacBio coverage should be 10x.
ONT is also around 10x
**buildGraph.err** lists:
`estimated average coverage 11.7946
assembly size 1071615368 bp, N50 15182`
size is surprisingly 3-4x smaller than expected.

Versions:
<pre>Launching bioconda verkko bioconda 2.0
Using snakemake 7.32.4.</pre>

MBG reported by conda: 1.0.16  hdcf5f25_0  
MBG installed manually through conda, can't tell actual version as
`>MBG --version`
Gives:
<pre>MBG Branch  commit
Version: Branch  commit</pre>

**Comment by skoren** [comment]
Can you share your 1-buildGraph and 2-processGraph folders (https://canu.readthedocs.io/en/latest/faq.html#how-can-i-send-data-to-you)?

**Comment by grinning-bat** [comment]
Done:
`63e8a64b010d71d081489783f01d0782  build_graph_1426.tgz
24a723bf5e324064d2d12103aed28414  process_graph_1426.tgz`

**Comment by skoren** [comment]
@maickrau it seems there's a node in the graph that's getting cut but it still has an edge to it in extra_nocut_edges. So first, the edge is added to and then the neighboring node is cut. It seems like the graph is reasonable if you just skip adding the edge (e.g. continue rather than assert). I posted the data on globus under issue230, can you take a look?

**Comment by maickrau** [comment]
The haplotype gap fixing had reads supporting two different fixes at the het nodes and the fixes were not compatible, so it crashed when it tried to apply both fixes. Commit [91070e8](https://github.com/marbl/verkko/commit/91070e8eb79cf4b7717fc07662b7089e1b7a8336) now checks if it tries to include conflicting fixes and only includes one of them.

Also in general the graph looks very fragmented, probably due to low HiFi coverage. It seems like the average coverage per haplotype might be around 5x or even lower, so getting around 3 times more HiFi data would probably improve the assembly a lot.

**Comment by grinning-bat** [comment]
Tried it, processGraph works now. Great! Thanks a lot!
We aimed at 10x HiFi and 10x ONT, but intracellular parasites steal too much coverage. Probably we will do some additional sequencing indeed.
