### ISSUE TITLE
Test with different ont data

### ISSUE THREAD

**Issue by oushujun** [marbl/verkko#45]
Hello,

Thanks for developing this exciting assembler and making it available. I am trying it on some tomato data and would like to test on different ONT data filtered by various length and quality scores. The HiFi data is the same. For the sake of time, can I reuse the previous steps, ie., retain folders 0-3, and remove 4 and after, for everytime I try on a new ONT dataset?

In general, what `--min-ont-length` and coverage is recommended to fully harnish the power of super-long reads and verkko?

Some super-long ONT reads have quite low average Q scores (i.e., <5), are those useful or should I remove them? Maybe a feature that verkko can add (i.e., --min-ont-qscore)?  

Thanks again!
Shujun

**Comment by skoren** [comment]
The 3- step will change based on your input ONT data since that is when it is split/aligned. Since ONT alignments is one of the longest time sinks, I would personally run the first assembly using all HiFi and all ONT data. Then, for subsequent runs, keep the 0-2 folders but subset the alignments in the 3- step to only include the ONT reads you want to subset to. This also has the advantage that you'll control for some random known behavior in GraphAligner. Make sure to use `--snakeopts "--dry-run"` to make sure it will run just the steps you're interested in before you launch it for real.

We typically use all ONT reads, if they are low quality the should not align and/or will get outvoted. As for length, anything longer than HiFi reads can help but again, we let the alignment decide if it's useful.

**Comment by oushujun** [comment]
Hi Sergey,

Can you provide more details on how to subset alighments in the 3- step? What files do I need to modify? Thanks!

Shujun

**Comment by skoren** [comment]
The file you'd want to subset is `3-align/alns-ont.gaf`. It'll have read IDs as the first column so you can just subset it to only include the reads you want to include in the subset. If you make a copy of your snakemake assembly dir, you will probably need to run touch then dry-run to confirm it will run the right jobs, unless you preserve timestamps. Something like:
```
cp -rp asm asm_subset
rm -rf asm_subset/assembly.*
rm -rf asm_subset/4-*
rm -rf asm_subset/5-*
rm -rf asm_subset/6-*
rm -rf asm_subset/7-*
```
then manually edit/subset the file above and re-launch:
```
verkko -d asm_subset --hifi <input> --nano input --snakeopts "--dry-run"

Launching verkko branch master commit 1633e6e5a07202e64ff48c3866ab0fc05c308d7d 2022-02-03 20:09:40 -0600 ... 
...
Job stats:
job                  count    min threads    max threads
-----------------  -------  -------------  -------------
buildPackages            1              8              8
combineConsensus         1              1              1
extractONT               1              8              8
getFinalCoverages        3              1              1
layoutContigs            1              1              1
prepCoverage             1              1              1
processONT               1              1              1
untip                    1              1              1
verkko                   1              1              1
total                   11              1              8

This was a dry-run (flag -n). The order of jobs does not reflect the order of execution.
```

**Comment by oushujun** [comment]
Thanks! Will give it a try once I got a full run done. - Shujun

**Comment by oushujun** [comment]
So I tried the full dataset and one with only longer ont reads:
Here is the full dataset read length distribution:
![image](https://user-images.githubusercontent.com/5996084/156068557-b58a427b-3123-4d0b-b5f0-c2355d6553eb.png)

The assembly is quite good:
![image](https://user-images.githubusercontent.com/5996084/156068633-abac6c96-ddd7-492a-8e10-4652d67114b5.png)

I used ont reads with q>20, length ≥ 50kb, which is around 20x, and the longer contigs broke into smaller pieces:
![image](https://user-images.githubusercontent.com/5996084/156068881-92e6da68-cd06-4f8f-8827-f05891dc2d57.png)

The conclusion of this experiment is using only long ONT reads (instead of all reads of the same dataset) did not make the assembly more continuous, but did reduce the number of small contigs. Any comments?

**Comment by skoren** [comment]
I'm not sure what you mean by "didn't make the assembly more continuous"? Aren't the large contigs losing pieces when you lower the coverage which implies it's less continuous? I'd guess this is happening in regions with gaps due to HiFi sequencing drop out. In these cases, you don't need very long reads to resolve the gap but lowering the coverage could lose you the reads you needed to bridge the gap.

The larger number of short contigs is likely due to errors in the reads, at sufficient coverage they don't get filtered out and are retained but they're disconnected from the graph and short.

**Comment by oushujun** [comment]
Right, I thought using only long ONT reads would lower the computation burden (it did) and increase the contiguity (it didn't). So shorter ONT reads did help to connect some HiFi contigs.

**Comment by skoren** [comment]
Yes, we've seen that some shorter ONT reads are helpful which is why we typically run with all data. The long alignment time is a known issue and we plan to improve that in future versions.
