### ISSUE TITLE
the assembly length is more than the actual length

### ISSUE THREAD

**Issue by zhoudreames** [marbl/verkko#59]
I extracted the local hifi and ont reads from a length of ~12Mb region， then run the verkko with default parameters. However, I obtain more than 100Mb assembled sequence, and it far exceed the length of the actual region.

input：
The hifi data :3.3Gb(mean coverage ~30X) ;the Ont data:5.4Gb(mean coverage ~50X)
output：
assembly.fasta(108Mb with 68 contigs)

**Comment by zhoudreames** [comment]
I know

**Comment by zhenyu7500** [comment]
I have the same problem, could you tell me how to solve it? 

Thank you.

**Comment by skoren** [comment]
Need more details than that, the original issue was subsetting a targeted 12mb region. Are you doing the same or running a whole genome assembly. What is the input data/coverage, what is the output size you expect, what is the actual output size.

**Comment by zhenyu7500** [comment]
The genome size of the specie we assembled is about 1g, but the output assembly. Fasta is 1.8 gb. I tried purge_dups for  purgeing haplotigs , but the output purged.fa was still 1.8g.  Since pluge_dups seems to only accept Pacbio read, I didn't input Ont read. I don't know if it makes a difference. could you give me some advice?

Thank you.

**Comment by skoren** [comment]
The output of verkko is phased contigs so this sounds like you got both haplotypes in the assembly. Do you have trio or Hi-C or other long-range information for phasing these further? 

If not, keep in mind the contigs will be relatively shorter since verkko doesn't build a pseudo-haplotype like other assemblers. You need to run purge_dups to get a single haplotyp for now. It often fails to set thresholds correctly for fully phased assemblies so I guess this is what happened here. See https://github.com/marbl/canu/issues/1814 and https://github.com/dfguan/purge_dups/issues/38 for some discussions on how to select appropriate cutoffs.

**Comment by zhenyu7500** [comment]
Unfortunately, we don't have trio or Hi-c or other long-range information. Thank you for your reply. 
By the way, can the Hi-C data from Different individuals (same breed) be used to link contigs to scaffolds?

**Comment by skoren** [comment]
Yes, you can use Hi-C from different individuals to scaffold the assembly but not for phasing. You should also look at the assembly graph generated as it already be close to scaffolded, just unphased (that is long homozygous regions stop contigs not gaps). 

Depending on how much effort you wanted to put into this assembly and/or how diploid/connected the graph looks, you may be able to manually generate some paths to increase the assembly contig sizes. Verkko can generate consensus for arbitrary paths in the graph for you.

**Comment by zhenyu7500** [comment]
Thank you very much for your help!

**Comment by zhenyu7500** [comment]
Daer skoren,
I am sorry that there are still some problems.
From the PB.stat file got by pluge_dups, we I got the picture below.
![image](https://user-images.githubusercontent.com/58357900/169696941-312183fb-ca5f-4949-94a9-7bfe766e502c.png)
Only in 9 there is a peak.  But what we've assembled is a diploid bird. 
The model shown in this figure is different from other diploid organisms. I don't know how to set cutoffs.
Thank you in advance for your reply.

**Comment by skoren** [comment]
Yes, that's exactly the issue discussed in the issues I linked. The assemblies are completely phased so there's no double peak. Did you read through them, they provide guidance on setting the cutoffs in this case. I'd set the lower cutoff to 1 or 2 (you have pretty low hifi coverage) and the middle one at 16-18, the high can be 34 or higher. You may need to experiment with a few cutoffs.

**Comment by zhenyu7500** [comment]
Hi，Thanks a lot for your reply.
I found that the reason why the perge_dups did not purge redundant haplotypes is that the naming rule of the contig name: there is a  punctuation "-" in unassigned-000XXXX. After remove "-", perge_dups works well. I don't know if this situation I encountered is an exception.
We found that the N50 of the assemblied by verkko was only 1m and the N50 got by hifiasm is about 6m. 
I know that verkko prefers build haplotype assembly,  but is this normal?  (since we use hifi and ont ultra long read together )

thank you very much!

**Comment by skoren** [comment]
Ah, I didn't realize purge_dups can't handle '-' in the name. As for N50 sizes, verkko output is completely phased so the size of the contigs will depend on how long your reads are and how much heterozygosity is present in your species. hifiasm contig output is not phased at all, it make a randomly joined pseudohaplotype (unless you use HiC or trio which. you can also use with verkko). The comparable output to verkko from hifiasm is the unitigs it generates.
