### ISSUE TITLE
empty sequence in assembly.fasta

### ISSUE THREAD

**Issue by comery** [marbl/verkko#66]
Hi there,

This assembler looks very good to handle ONT and hifi reads to generate a continuous and high-quality assembly. I am trying to use it in my project.

I see a tiny bug in the assembly result. see below picture. There is an empty sequence in both "assembly.fasta" and "assembly.unassigned.fasta" which is not supposed to show. I would like to let you know that.
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/8231694/165666616-cbcc0b4e-449b-421b-b67d-4fabba1b04de.png">

**Comment by skoren** [comment]
That shouldn't happen, what is the version of verkko you're running and how was it installed?

**Comment by comery** [comment]
I installed it using conda. it seems that the version is 1.0 from the log "Launching bioconda verkko bioconda 1.0 ...".

**Comment by skoren** [comment]
@ptrebert I would guess this is a short contig that's unassigned to a haplotype. It's probably safe to ignore it, it likely had few reads and ended up with no coverage in consensus but it should still be removed from the output in that case.

Can you track it down to a consensus package, assuming you have it's id, say `unassigned-0001322`, look for it in the `6-layoutContigs/*scfmap` file and then track it to a partition:
```
% grep -C 5 unassigned-0001322 6-layoutContigs/*scfmap
piece009476
end
path haplotype1-0001321 mat_unused_utig4-9997
piece009484
end
path unassigned-0001322 na_unused_utig4-100
piece000181
end
path unassigned-0001323 na_unused_utig4-1000
piece001066
end
% grep -w piece000181 7-consensus/packages.tigName_to_ID.map 
147  piece000181
% at 7-consensus/buildPackages.err |awk '{if ($1 == 147) print $0}'
--------------------- TIG -------------------  ------- PARTITION --------  maxArea:  302924655602928
    ID   Reads    Length         Area Mem(GB)    ID   Total Area TotReads  maxReads: 3396781
------ ------- --------- ------------ -------  ---- ------------ --------
   147       3     24989       112450   0.036     4 302870418058666  2604824
```
This means it has 3 reads and is in partition 4. Assuming it's just a few reads, you can grep -A number of reads + 3, e.g. here is 6:
```
% grep -A 6 piece000181 6-layoutContigs/unitig-popped.layout
tig     piece000181
len     24989
rds     3
m64015e_210224_100310/66782126/ccs      18472   0
m64076_201016_191536/107546301/ccs      11649   24989
m64014_210227_165255/12124848/ccs       12327   24084
end
```
Consensus requires at least 2x coverage to output a sequence so in this case it gets trimmed since the first 11kb and the last 1kb don't have 2x coverage (24k-11kb-1kb = 12kb). If you could post the info on the tig of the reads here and upload the package file to the FTP (see https://canu.readthedocs.io/en/latest/faq.html#how-can-i-send-data-to-you) or globus (you might have to re-run buildPackages.sh) we can see what is going on in consensus.

**Comment by ptrebert** [comment]
what an exceptional debugging guide :astonished: 
ok, I have identified the relevant pieces of information...

```
tig     piece000449
len     15824
rds     2
m64039_220109_212617/148440232/ccs      0       15824
m64119_211225_064020/117506429/ccs      13717   2029
end
```
That situation seems to be what you predicted. Also, looks like I need to run `buildPackages.sh` to share the package file. Since I won't be available in the next two weeks, I am not sure I can provide that before I leave...

**Comment by skoren** [comment]
Yeah so I'd say you can definitely ignore that empty sequence and use the assembly you have w/o it but this should be enough for us to reproduce/fix locally.

**Comment by ptrebert** [comment]
Thanks for this assessment; as an immediate solution, I am going to proceed with the modified assembly, then.

**Comment by brianwalenz** [comment]
The above commit (84d683630ae4a6198136c198737db6a23ac59f6a) will strip any empty sequences from the output fasta and write a message to `7-consensus/combineConsensus.err`, e.g.:
```
ERROR: contig unassigned-0000598 is empty.
```
The underlying "problem" still exists.

**Comment by skoren** [comment]
What happens if the empty contig was part of a large scaffold? Does this cause an error in the pipeline or will it lose the entire scaffold?

**Comment by brianwalenz** [comment]
It should generate an error and fail.  Should be easy to make it generate a warning and merge the adjacent gaps into one though.

**Comment by skoren** [comment]
Failing is good in those cases I think so lets leave it like this and consider resolved for now

**Comment by ptrebert** [comment]
Just FYI, I downloaded a HG002 Verkko assembly from the T2T Globus
```
/assemblies/drafts/wip/HG002/verkko/Full_Coverage/v1.0/
```
and I just stumbled upon the same problem/bug for this one as well:
![image](https://user-images.githubusercontent.com/36245614/176373430-58be3709-a0a0-49a8-b11b-ad98d01c0ff5.png)
