### ISSUE TITLE
(core dumped) miniconda3/envs/verkko/bin/MBG $iopt

### ISSUE THREAD

**Issue by hrluo93** [marbl/verkko#83]
Dear verkko,

I have manually run buildGraph.sh following the suggestion given by #80, but still core dumped errors
[nohup.out.txt](https://github.com/marbl/verkko/files/9054292/nohup.out.txt)

MBG: src/ConsensusMaker.h:65: void ConsensusMaker::addStrings(size_t, size_t, size_t, F) [with F = addCounts(ConsensusMaker&, const SequenceCharType&, const SequenceLengthType&, const string&, size_t, size_t, size_t, size_t, size_t, bool)::<lambda(size_t)>; size_t = long unsigned int]: Assertion `compressedSequences[realUnitig].get(realOff) == 0 || compressedSequences[realUnitig].get(realOff) == compressed' failed.

buildGraph.sh: line 39: 105413 Aborted                 (core dumped) /home/tilapia/miniconda3/envs/verkko/bin/MBG $iopt -t 4 -k 1001 -r 15000 -R 4000 -w 100 --kmer-abundance 1 --unitig-abundance 2 --error-masking=collapse-msat --output-sequence-paths ../1-buildGraph/paths.gaf --out ../1-buildGraph/hifi-resolved.gfa

I have checked the MBG version 
/home/tilapia/miniconda3/envs/verkko/bin/MBG
MBG bioconda 1.0.11

should I manually install MBG by hand? Or does my ccs.fa had some problems?

Best wishes!

Ran

**Comment by skoren** [comment]
You need to install MBG by hand from the repo rather than using bioconda.

**Comment by hrluo93** [comment]
> You need to install MBG by hand from the repo rather than using bioconda.

Thanks for your reply! I will try it!

Best!

Ran

**Comment by xianjia10** [comment]
Hi,I have the same question.But still got the same error when I did as you suggested.
###
MBG: src/ConsensusMaker.h:65: void ConsensusMaker::addStrings(size_t, size_t, size_t, F) [with F = addCounts(ConsensusMaker&, const SequenceCharType&, const SequenceLengthType&, const string&, size_t, size_t, size_t, size_t, size_t, bool)::<lambda(size_t)>; size_t = long unsigned int]: Assertion `compressedSequences[realUnitig].get(realOff) == 0 || compressedSequences[realUnitig].get(realOff) == compressed' failed.
Aborted (core dumped)
###
My MBG version is 
MBG  1.0.11 (installed by MBG/[Releases](https://github.com/maickrau/MBG/releases) [v1.0.11])
when i install MBG with git ,also appear the same error
does my hifi-data had some problems?or what should i do?

**Comment by skoren** [comment]
If your version reports release/1.0.11 as the version that is not the tip I suggested running as a test. You need to check it out and built it from source following the instructions here: https://github.com/maickrau/MBG#compilation. It should report version as something like:
```
MBG Branch master commit 06d9bbe3f7fe31aa9dcac7f69aa98fccd714e100 2022-07-16 09:59:58 -0400
Version: Branch master commit 06d9bbe3f7fe31aa9dcac7f69aa98fccd714e100 2022-07-16 09:59:58 -0400
```

**Comment by xianjia10** [comment]
> 

My buildGraph.err is 

Building graph with reads:
  ../hifi-corrected.fasta.gz


MBG Branch master commit 06d9bbe3f7fe31aa9dcac7f69aa98fccd714e100 2022-07-16 09:59:58 -0400
Parameters: k=1001,w=100,a=1,u=2,t=4,r=15000,R=4000,hpcvariantcov=25,errormasking=collapse-msat,endkmers=no,blunt=no,keepgaps=no,guesswork=yes,cache=no
Collecting hpc variant k-mers
Reading sequences from ../hifi-corrected.fasta.gz
528423251 total selected k-mers in reads
18372529 distinct selected k-mers in reads
Reading sequences from ../hifi-corrected.fasta.gz
Reading sequences from ../hifi-corrected.fasta.gz
MBG: src/ConsensusMaker.h:65: void ConsensusMaker::addStrings(size_t, size_t, size_t, F) [with F = addCounts(ConsensusMaker&, const SequenceCharType&, const SequenceLengthType&, const string&, size_t, size_t, size_t, size_t, size_t, bool)::<lambda(size_t)>; size_t = long unsigned int]: Assertion `compressedSequences[realUnitig].get(realOff) == 0 || compressedSequences[realUnitig].get(realOff) == compressed' failed.
Aborted (core dumped)

I think this version is you suggested 
Since it still had the same error, I passed  MBG/Releases[v1.0.11] to install MBG 
this report vesion:
"""
MBG Branch  commit
Version: Branch  commit
"""
But it also show the same error log.

**Comment by xianjia10** [comment]
> If your version reports release/1.0.11 as the version that is not the tip I suggested running as a test. You need to check it out and built it from source following the instructions here: https://github.com/maickrau/MBG#compilation. It should report version as something like:
> 
> ```
> MBG Branch master commit 06d9bbe3f7fe31aa9dcac7f69aa98fccd714e100 2022-07-16 09:59:58 -0400
> Version: Branch master commit 06d9bbe3f7fe31aa9dcac7f69aa98fccd714e100 2022-07-16 09:59:58 -0400
> ```

>


My buildGraph.err shows that

Building graph with reads:
  ../hifi-corrected.fasta.gz


MBG Branch master commit 06d9bbe3f7fe31aa9dcac7f69aa98fccd714e100 2022-07-16 09:59:58 -0400
Parameters: k=1001,w=100,a=1,u=2,t=4,r=15000,R=4000,hpcvariantcov=25,errormasking=collapse-msat,endkmers=no,blunt=no,keepgaps=no,guesswork=yes,cache=no
Collecting hpc variant k-mers
Reading sequences from ../hifi-corrected.fasta.gz
528423251 total selected k-mers in reads
18372529 distinct selected k-mers in reads
Reading sequences from ../hifi-corrected.fasta.gz
Reading sequences from ../hifi-corrected.fasta.gz
MBG: src/ConsensusMaker.h:65: void ConsensusMaker::addStrings(size_t, size_t, size_t, F) [with F = addCounts(ConsensusMaker&, const SequenceCharType&, const SequenceLengthType&, const string&, size_t, size_t, size_t, size_t, size_t, bool)::<lambda(size_t)>; size_t = long unsigned int]: Assertion `compressedSequences[realUnitig].get(realOff) == 0 || compressedSequences[realUnitig].get(realOff) == compressed' failed.
Aborted (core dumped)

I think this version is you suggested 
Since it still had the same error, I passed  MBG/Releases[v1.0.11] to install MBG 
this report vesion:
```
MBG Branch  commit
Version: Branch  commit
```
But it also show the same error log.

**Comment by skoren** [comment]
Are you able to share your hifi-corrected.fasta.gz inputs? See the canu FAQ for sending files to us: https://canu.readthedocs.io/en/latest/faq.html#how-can-i-send-data-to-you

**Comment by xianjia10** [comment]
> Are you able to share your hifi-corrected.fasta.gz inputs? See the canu FAQ for sending files to us: https://canu.readthedocs.io/en/latest/faq.html#how-can-i-send-data-to-you

I can't upload my hifi-corrected.fasta.gz ,because 553 Could not create file 
There are some hifi-reads's fraction:

>m64144_220310_093854/7/ccs
tcgtgctatgtatgtatctagatctctgtcactctcatcagtctctctgtgtgagcgtgatctgcagcgtcactagctcgatcatgacgagcagtatcagtatgcacagatctcatctgcatcagtgtcgcgcgcagctactacgcgtgtagtcgacgcgctgacacgacatcgtctag
>m64144_220310_093854/14/ccs
cactactctgatgagcacatcatcgagatcacatcagtctgtgtctagagatcagatcgagagatctgatctatagacgcagctatagtactgctgtcatactcagtgtgatgagcagagtctagctctacactgatcacgatgcacagagatacgagtgagctcagagtcgacatagt
>m64144_220310_093854/15/ccs
acgagatatatatatcgtagcgtagcgatcatagatctagcatgtatcgctatactcgatacgctctatatagatatagcagtagatatacacagagctatatgctatgcacagatctatatagcatacatatcatcagtgtatagatagtagtatcagatagatcgctgactcgatac

And I have checked the reads sequence, they don't have any characters other than ATCG. Could this be the reason for the reads name ?

**Comment by maickrau** [comment]
Sometimes this crash happens if the input has duplicate reads. Could you please check for duplicate reads with this script:

```zcat hifi-corrected.fasta.gz | grep '>' | cut -d " " -f 1 | sort | uniq -c | sort -nr | head -n 1```

If the first number is anything other than 1, then there are duplicate reads in the input and you need to make sure that each read appears only once in the input.

**Comment by xianjia10** [comment]
> Sometimes this crash happens if the input has duplicate reads. Could you please check for duplicate reads with this script:
> 
> `zcat hifi-corrected.fasta.gz | grep '>' | cut -d " " -f 1 | sort | uniq -c | sort -nr | head -n 1`
> 
> If the first number is anything other than 1, then there are duplicate reads in the input and you need to make sure that each read appears only once in the input.

Thanks a lot . 
I follow you suggestions to run that script ,the first number is 2.and show 
'''
 2 >m64144_220310_093854/999/ccs
'''
So I need to remove a duplicate read ?

**Comment by skoren** [comment]
Yes you'd need to remove the second copy of the read. Are the two reads the same length or different? If you still have the `0-* `folder, can you check the hifi.seqStore/readNames.txt file for that ID?

**Comment by xianjia10** [comment]
> Yes you'd need to remove the second copy of the read. Are the two instances the same length or different? If you still have the `0-* `folder, can you check the hifi.seqStore/readNames.txt file for that ID?

I have removed the second copy of the read.I am trying to run `buildGraph.sh` again.
The two instances are the same length.
The `0-*` folder is automatically removed when generating `hifi-corrected.fasta.gz` ,so I can't check that file you mentioned.

**Comment by xianjia10** [comment]
> Yes you'd need to remove the second copy of the read. Are the two instances the same length or different? If you still have the `0-* `folder, can you check the hifi.seqStore/readNames.txt file for that ID?

I have re-run verkko ,but I still have the same question.  I follow you suggestions to run that script to make sure that each read appears only once in the input. ,but when i check each read ,I found that each read appears twice. 
I'm wondering why this problem occurs ?

**Comment by woshiakai5525** [comment]
I still have this problem even I have update verkko to version1.2. The error message as below.

######
MBG: src/MBG.cpp:1482: sortPaths(std::vector<ReadPath>&)::<lambda(const ReadPath&, const ReadPath&)>: Assertion `false' failed.
./buildGraph.sh: 41 行: 391056 中止                  (コアダンプ) /home/gikenbio/.pyenv/versions/anaconda3-5.3.1/envs/verkko/bin/MBG $iopt -t 4 -k 1001 -r 15000 -R 4000 -w 100 --kmer-abundance 1 --unitig-abundance 2 --error-masking=collapse-msat --output-sequence-paths ../1-buildGraph/paths.gaf --hpc-variant-onecopy-coverage 25 --do-unsafe-guesswork-resolutions --out ../1-buildGraph/hifi-resolved.gfa
######

I also had a check for duplicate reads as below.

######
zcat output/hifi-corrected.fasta.gz | grep '>' | cut -d " " -f 1 | sort | uniq -c | sort -nr | head -n 1
1 >m64281e_220717_184251/99945307/ccs
######

I appreciate if anybody could give me more help.

**Comment by skoren** [comment]
@woshiakai5525 your issue is not a duplicate read, it's a different error message. It looks like you are using a conda version of MBG so the suggestion of updating to the latest MBG from the GitHub repo might help, rather than installing it from conda.

**Comment by skoren** [comment]
I added a check for this so should disallow duplicate reads in input.
