### ISSUE TITLE
Re-run verkko start from 0-correction again instead of continue the  job stopped before

### ISSUE THREAD

**Issue by zou-yawen** [marbl/verkko#86]
Hi,I have a question.Every time verkko stop because of some error ,When rerun verkko, it will start from 0-correction again instead of continue the  job stopped before.I`m very confused. And sometime the directory of 0-correction some disappear .Could you please give me chematic diagram of the analysis process.
Looking forward your reply.
Best wishes.

**Comment by skoren** [comment]
The 0-step is HiFi correction, it has a few subsets (k-mer counts, overlaps, correction) and it gets cleaned up as soon as the hifi.corrected.fasta file exists. Usually, when snakemake tries to go back to an earlier step it's because something either got manually changed in the folder or the input data got updated/touched. 

I would suggest running verkko with the `--snakeopts "--touch"` and `--snakeopts "--dry-run"` which will make sure the timestamps are consistent and will let you check what steps will run before actually running anything. It will also report why it's running every step. If it keeps going to the wrong step, post the log from dry-run here. You can also run w/--keep-intermediates which will not do any cleanup.

**Comment by zou-yawen** [comment]
> The 0-step is HiFi correction, it has a few subsets (k-mer counts, overlaps, correction) and it gets cleaned up as soon as the hifi.corrected.fasta file exists. Usually, when snakemake tries to go back to an earlier step it's because something either got manually changed in the folder or the input data got updated/touched.
> 
> I would suggest running verkko with the `--snakeopts "--touch"` and `--snakeopts "--dry-run"` which will make sure the timestamps are consistent and will let you check what steps will run before actually running anything. It will also report why it's running every step. If it keeps going to the wrong step, post the log from dry-run here. You can also run w/--keep-intermediates which will not do any cleanup.

Thank you very much.I try the parameter --keep-intermediates,it works well.

**Comment by skoren** [comment]
The default now will run keeping intermediate outputs (can be optionally re-enabled) and cleanup is deferred till after snakemake is done to avoid these issues.
