### ISSUE TITLE
sacct error

### ISSUE THREAD

**Issue by fjruizruano** [marbl/verkko#93]
Hi!

I am running this command to run verkko with Slurm

`
verkko -d /out/directory --hifi hifi_reads.fastq --nano ont_reads.fastq --slurm --snakeopts '--cluster "sbatch -p core -n 20 -A projectXXX -t 24:00:00 --mail-type=FAIL,TIME_LIMIT_80 --mail-user=myemail@mail.com"' --hap-kmers mat.hapmer.meryl pat.hapmer.meryl trio
`

And I got this error

```
sacct: fatal: Bad job/step specified: Submitted batch job 28816845
Job Submitted batch job 28816845 is  (by default).
```
A job is submitted to the queue, but the pipeline doesn't continue after it.
Any clue?

Thanks in advance,
Francisco.

**Comment by skoren** [comment]
Your command overwrite the default cluster submission in verkko: https://github.com/marbl/verkko/blob/master/src/profiles/slurm-sge-submit.sh which means the return value of the job id couldn't be parsed by snakemake. You need the `--parsable` option on your sbatch command. 

In general, with more recent versions of snakemake, you should edit the submission command in the profile to add your options rather than doing on the command line.

**Comment by skoren** [comment]
Idle
